version: '3'
services:
  Web_Host:
    image: alpine:latest
    container_name: Tomcat_Web_Host
    ports:
      - 8080:8080
    volumes:
      - C:/Repos/Demo_Tic_Tac_Toe/Tick_Tack_Toe_Environment/Testing/Volumes/TomcatConfig/tomcat-users.xml:/myfile/tomcat-users.xml
      - C:/Repos/Demo_Tic_Tac_Toe/Tick_Tack_Toe_Environment/Testing/Volumes/TomcatConfig/context.xml:/myfile/context.xml
      - C:/Repos/Demo_Tic_Tac_Toe/Tick_Tack_Toe_Environment/Testing/Volumes/BasicJspProject/HelloWorldOnServer.war:/myfile/HelloWorldOnServer.war
      - C:/Repos/Demo_Tic_Tac_Toe/Tick_Tack_Toe_Environment/Testing/Volumes/BasicJspProject/background.gif:/myfile/background.gif

    command: >
      /bin/sh -c "
        apk update &&
        apk add openjdk17-jre &&
        java -version &&
        mkdir /opt/tomcat &&
        apk add wget &&
        wget https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.0/bin/apache-tomcat-10.0.0.tar.gz &&
        tar xvzf apache-tomcat-10.0.0.tar.gz --strip-components 1 --directory /opt/tomcat &&
        cp /myfile/tomcat-users.xml opt/tomcat/conf/ &&
        cp myfile/context.xml opt/tomcat/webapps/manager/META-INF/ &&
        cp myfile/HelloWorldOnServer.war opt/tomcat/webapps/ &&
        cd /opt/tomcat/bin &&
        chmod +x startup.sh &&
        ./startup.sh &&
        tail -F anything
      "
  Bot1:
    
    image: alpine:latest
    container_name: Bot1
    command: >
      /bin/sh -c "
        apk update &&
        apk add openjdk17-jre &&
        java -version &&
        tail -F anything
      "
  Bot2:
    image: alpine:latest
    container_name: Bot2
    command: >
      /bin/sh -c "
        apk update &&
        apk add openjdk17-jre &&
        java -version &&
        tail -F anything
      "